AllCops:
  TargetRubyVersion: 2.5.5

Bundler/OrderedGems:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 50
  Exclude:
  - db/migrate/*.rb

Metrics/BlockLength:
  Exclude:
  - spec/**/*.rb  

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

inherit_from: .rubocop-excludes.yml
