version: '3'
services:
  shastic_challenge:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    links:
      - mysql
    volumes:
      - ./:/app
    stdin_open: true
    tty: true
    environment:
      - DEVELOPMENT_DATABASE=shastic_challenge_development
      - TEST_DATABASE=shastic_challenge_test
      - BASE_DATAFEED_URL=http://www.mocky.io/v2/

  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    command: [mysqld, --character-set-server=utf8, --collation-server=utf8_unicode_ci]
    ports:
      - 3306:3306
    volumes:
      - ./:/app
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
